### ISSUE TITLE
Open source firmware

### ISSUE THREAD

**Issue by louiecaulfield** [john30/ebusd-esp#85] opened 2023-10-04 17:00 UTC
Sorry if this question has been asked (and answered) elsewhere before - I couldn't find it.

Are there any plans to open source the firmware running on the ebus adapter?

I just received my V5 and would love to go hacking about :-)

**Comment by BartoszKordylewski** [comment] 2023-10-23 22:29
Yup, me too - I would love to somehow connect it with SUPLA system, SUPLA has integration with Arduino (ESP etc.), but for eBUS there is nothing to just take and edit...

**Comment by john30** [comment] 2024-01-06 17:11
duplicate of #5

**Closed by john30** 2024-01-06 17:11 UTC
